### ISSUE TITLE
Install as a Ansible collection

### ISSUE THREAD

**Issue by gardar** [netson/ahvl#1]
It would be great to be able to install these modules/plugins as a Ansible collection with ansible-galaxy as opposed to pip.

Helpful links:
https://docs.ansible.com/ansible/latest/user_guide/collections_using.html
https://docs.ansible.com/ansible/latest/dev_guide/developing_collections.html

**Comment by netson** [comment]
Hey, thanks for the feedback. I agree and this has been on my list for a while, but I simply don't have the time right now. I'd be more than happy to review/accept PR's though, so if you want to take a stab at it, please do! :-)

The module has been running in a production environment for more than a year now without any issues, so even going the pip route could be worth your while! This ensures I use unique and random secrets for pretty much everything, every service, every user, every account, every database, without the hassle of generating and storing them. I just spin up a new instance and know that my passwords are random and secure and if I ever need then, I use the Vault UI to find them! :-)

**Comment by gardar** [comment]
Ok now we are getting somewhere.

I copied
```
ahvl/ahvl/options/lookup/credential.py       ->    ~/.ansible/plugins/lookup/ahvl_credential/ahvl_credential.py
ahvl/ahvl/options/lookup/gpgkey.py           ->     ~/.ansible/plugins/lookup/ahvl_gpgkey/ahvl_gpgkey.py
ahvl/ahvl/options/lookup/password.py        ->     ~/.ansible/plugins/lookup/ahvl_password/ahvl_password.py
ahvl/ahvl/options/lookup/sshhostkey.py      ->     ~/.ansible/plugins/lookup/ahvl_sshhostkey/ahvl_sshhostkey.py
ahvl/ahvl/options/lookup/sshkey.py             ->     ~/.ansible/plugins/lookup/ahvl_sshkey/ahvl_sshkey.py
```

And now it seems to load the lookup plugin, but I'm now faced with another error:

```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: module 'ansible.plugins.lookup.ahvl_password' has no attribute 'LookupModule'
failed: [localhost] (item=plaintext) => {"ansible_loop_var": "item", "item": "plaintext"}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: module 'ansible.plugins.lookup.ahvl_password' has no attribute 'LookupModule'
failed: [localhost] (item=hexsha256) => {"ansible_loop_var": "item", "item": "hexsha256"}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: module 'ansible.plugins.lookup.ahvl_password' has no attribute 'LookupModule'
failed: [localhost] (item=hexsha512) => {"ansible_loop_var": "item", "item": "hexsha512"}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: module 'ansible.plugins.lookup.ahvl_password' has no attribute 'LookupModule'
failed: [localhost] (item=sha256crypt) => {"ansible_loop_var": "item", "item": "sha256crypt"}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: module 'ansible.plugins.lookup.ahvl_password' has no attribute 'LookupModule'
failed: [localhost] (item=sha512crypt) => {"ansible_loop_var": "item", "item": "sha512crypt"}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: module 'ansible.plugins.lookup.ahvl_password' has no attribute 'LookupModule'
failed: [localhost] (item=phpass) => {"ansible_loop_var": "item", "item": "phpass"}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: module 'ansible.plugins.lookup.ahvl_password' has no attribute 'LookupModule'
failed: [localhost] (item=mysql41) => {"ansible_loop_var": "item", "item": "mysql41"}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: module 'ansible.plugins.lookup.ahvl_password' has no attribute 'LookupModule'
failed: [localhost] (item=postgresmd5) => {"ansible_loop_var": "item", "item": "postgresmd5"}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: module 'ansible.plugins.lookup.ahvl_password' has no attribute 'LookupModule'
failed: [localhost] (item=pbkdf2sha256) => {"ansible_loop_var": "item", "item": "pbkdf2sha256"}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: module 'ansible.plugins.lookup.ahvl_password' has no attribute 'LookupModule'
failed: [localhost] (item=pbkdf2sha512) => {"ansible_loop_var": "item", "item": "pbkdf2sha512"}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: module 'ansible.plugins.lookup.ahvl_password' has no attribute 'LookupModule'
failed: [localhost] (item=argon2) => {"ansible_loop_var": "item", "item": "argon2"}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: module 'ansible.plugins.lookup.ahvl_password' has no attribute 'LookupModule'
failed: [localhost] (item=grubpbkdf2sha512) => {"ansible_loop_var": "item", "item": "grubpbkdf2sha512"}
fatal: [localhost]: FAILED! => {"msg": "One or more items failed"}
```

Can you perhaps share how/where the rest of the files are located in your environment? :smiley:

**Comment by netson** [comment]
I doubt it, since I only have a single module which generates GPG keys:
```
# tree .
.
└── gpg_key.py
```
What I do find odd is the UNDOCUMENTED text behind the ahvl lookup plugins; even though on my end the documentation may not be correct (I may have copy/pasted and not updated the individual plugins), but at least it shows something.

The other main difference I see is you're using a newer ansible version which I have not yet tested with. You mentioned in your earlier post that you set up an Ubuntu 18 OS? If so, are you using the default ubuntu repo? I am using the official ansible ppa `deb http://ppa.launchpad.net/ansible/ansible/ubuntu bionic main`. I doubt that will be the issue though, since I have been using these lookup plugins since ansible version 2.4 or something and have never had the need to update them or make config changes when ansible was updated.

But to rule it out would you be willing to give it a go?

**Comment by netson** [comment]
Is it possible you installed AHVL for a different python version than the one ansible uses? Or that you installed AHVL with pip in a specific/different environment? Just thinking out loud here.

Also, just to confirm, could you paste your playbook as well?

Here's an example for the ahvl_password plugin:
```
---
# playbook to demonstrate ahvl_password

- hosts: localhost
  gather_facts: no

  vars:
    output_filters:
      - plaintext
      - hexsha256
      - hexsha512
      - sha256crypt
      - sha512crypt
      - phpass
      - mysql41
      - postgresmd5
      - pbkdf2sha256
      - pbkdf2sha512
      - argon2
      - grubpbkdf2sha512

  tasks:

  # the path in vault which will be searched is [hosts/localhost/mariadb] on the default mountpoint
  - name: 'ahvl_password : get password for MariaDB account with username myuser and show all outputs'
    debug:
      msg: "{{ lookup('ahvl_password', find='mariadb', in='myuser', out=item) }}"
    loop: "{{ output_filters }}"

  - name: 'ahvl_password : get password (length=8, type=phrase - will result in 8 words) for MariaDB account with username anotheruser and output the mysql41 hash'
    debug:
      msg: "{{ lookup('ahvl_password', find='mariadb', in='anotheruser', out='mysql41', pwd_length=20, pwd_type='phrase') }}"
```

**Comment by netson** [comment]
Just added the actual plugin files! :-)

https://github.com/netson/ahvl/tree/master/lookup_plugins

Sorry for the confusion; I have tried and tested this many times on different workstations I own, but always using the same ansible root repository which contains these files by default.

Let me know if it works now! :-)

**Comment by gardar** [comment]
Ok that explains a lot! :smile: 

The plugins work successfully now on both ansible 2.11.5 and 2.7.18! 
Well almost, looks like there are issues with some of the output filters.
The filters: `pbkdf2sha256`, `pbkdf2sha512`, `argon2`, `grubpbkdf2sha512` all give a similar error:

```
"msg": "An unhandled exception occurred while running the lookup plugin 'ahvl_password'. Error was a <class 'TypeError'>, original message: string argument without an encoding"
```

Let me know if you want this error tracked in another issue as it's perhaps unrelated to the installation.

**Comment by netson** [comment]
:-D

The new error messages could be related to missing dependencies; did you install all the requirements? Not all are required to run the basics, but some outputs require additional system packages or python libraries. Glad things are moving in the right direction now! :-)
